mingrammer/diagrams

- pyproject.toml
Fixes issue raised in #12 
P.S: Thanks for building this lib. I always wanted something like this 😍
> Add contextvars to pyproject.toml

- diagrams/__init__.py
Allow custom graph, node, and edge attributes to be passed in to the Diagram constructor. This allows the user to configure the output image using whatever configuration of attributes they would like.
> Allow custom dot attributes in Diagram constructor

- diagrams/__init__.py
- docs/guides/diagram.md
- tests/test_diagram.py
This allows you to have a consistent output filename, even if you decide
to tweak the diagram name.
> Allow an output filename to be passed to Diagram explicitly.

- docs/getting-started/installation.md
This PR updates the install docs to provide instructions for streamlined install of the `graphviz` package via [Chocolatey.org](www.chocolatey.org), the Windows package manager which is analogous to Homebrew for Mac.
> Add `choco install graphviz` tip for Windows users

- CONTRIBUTING.md
This PR adds information on how to resize your images when contributing.
It also applies a few formatting changes such as:
- Using named links to reduce clutter
- Folding the text at 80 characters for command line users
- Removing dollar signs in codeblocks if no command output is provided [<sup>\[MD014\]</sup>][md014]
[md014]: https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md014---dollar-signs-used-before-commands-without-showing-output
> Add resizing to contributing

- docs/guides/diagram.md
`graphviz` only support string or byte-like objects as value in attributes. The example was passing `fontsize` as `int` that throws `TypeError`.
Just fixing the example
> fix: graph_attr example

- diagrams/__init__.py
Fixes #95.
This fixes the issue of Edge attributes being overwritten by empty strings, causing default values to be replaced with Graphviz defaults.
* Only set Graphviz attributes if they are not empty strings
> Verify Edge attributes exist before setting

- diagrams/__init__.py
Fixes #93.
This PR addresses crashing on systems with FIPS enabled.
Changes:
* Replace MD5 hash with UUID Version 4
* Replace references to *hashid* with *nodeid*
> Replace MD5 Hash with UUID

- autogen.sh
There is not prerequisite check for the black linter which is used in the script.
> check for black linter in autogen.sh

- README.md
With the brand new release of GitPitch 4.0 the documentation for the [Diagrams-as-Code Markdown Widget](https://docs.gitpitch.com/#/diagrams/cloud-architecture) has moved to a new location. This PR updates the description and link for this integration. Cheers, David.
> New GitPitch 4.0 Diagrams-as-Code Widget doc link.

- diagrams/outscale/__init__.py
So I've test the code on my Machine and it seems I've forgot to add the __init__.py
Sorry about the inconvenience.
Signed-off-by: Matthias Gatto <matthias.gatto@outscale.com>
> add Outscale __init__.py

- docs/getting-started/examples.md
Fluentd was moved from logging to aggregator in the following PR: 
https://github.com/mingrammer/diagrams/pull/295
but the examples was not updated, this PR update the path in the examples.
> docs(website): update Fluentd path in examples

- docker/dev/Dockerfile
Updated the docker alpine image as it was previously using rc which is actually using python 3.10.0a5... which was raising several errors, I think it's better to stay on stable version to ensure that all the other dependencies are able to run.
Detail of the python version (It may change when you will check as the rc is always on the latest python version).
https://hub.docker.com/_/python/
I go with python:3-alpine which is now (when I write the PR) on 3.9.2.
I also added xgd-utils to solve warning.
> [Docker] Update to use latest stable python 3

- docs/getting-started/examples.md
- docs/guides/edge.md
Following PR521 I updated all the main/replica to primary/replica (except the one already done in the PR 521).
https://github.com/mingrammer/diagrams/pull/521
> docs(all): update from main to primary

- website/sidebars.json
As written in the title added IBM link in the side bar for the docs.
> fix(website): add IBM in the side menu

- CONTRIBUTING.md
Without black being installed, I get the error: black is not installed
> Add black tool requirement for autogen.sh

- docker/dev/Dockerfile
**Summary**
Docker fails to build due to `go get` deprecation.  This change addresses the deprecation and allows for a successful build by replacing `go get` with `go install somePackage/package@version.`
**Testing**
Successfully built the docker image on amd64 Ubuntu and arm64 M1 Mac.
> Fix For go get Deprecation

- diagrams/__init__.py
This is for readability of the generated dot.file, which helps debugging as well.
> Allow `node.id` to be specified and not automatically generated

- diagrams/__init__.py
- tests/test_diagram.py
adds a flag `autolabel` to diagram that would prepend the node type to the label. 
closes #376
for example
```
with Diagram("Autolabel test", autolabel=True):
PubSub("Topic") >> GCF("Labeler") >> SQL("Resources")
```
would generate
> autolabel flag in diagrams that modifies label

- scripts/resource.py
1. Fix resource warning in the destructor
```
/Users/REDACTED/.asdf/installs/python/3.10.0/lib/python3.10/subprocess.py:1067: ResourceWarning: subprocess 46612 is still running
_warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
2. Use preferred, non-legacy API per https://docs.python.org/3/library/subprocess.html#subprocess.call
3. Older call style no longer needed with Python 3.6+
> Prefer subprocess run over call

- CONTRIBUTING.md
There is a small typo in CONTRIBUTING.md.
Should read `cleaning` rather than `clearning`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, clearning -> cleaning

- diagrams/__init__.py
Closes: #733 
Added `strict` as an optional *(backwards compatible)* parameter.
> Rendering should merge multi-edges strictly 

- config.py
The PROVIDERS constant in config.py was missing a comma in the list which was causing autogeneration to fail. Found this while trying to add a new icon to onprem.
I expect this is going to cause a few updates.
> fix: Syntax error in config.py

- diagrams/c4/__init__.py
This allows in example adding hyperlinks to C4 diagrams, as requested on #604.
This also allows further customization for those elements.
> feat(c4) Allow adding attributes.

- tests/test_c4.py
When running tests for c4 the setUp() initialize a name variable that is used as name parameter for Diagram() class.
The name variable generated have upper case. ex: "diagram-e1Ad2eF"
In Diagram class when name parameter is provided it's used to generate a file in lower case.
filename = "_".join(self.name.split()).lower()
So when the tearDown is called and ask to remove the file using self.name with upper case, the file are not found so not removed.
os.remove(self.name + ".png")
It may work in windows as windows is case insensitive but not for linux.
> fix(tests): set lower for case sensitive system

- .github/workflows/test.yml
Install poetry with pip causes many issues. The recommended way is to use this curl script or pipx.
> Install poetry the right way

- diagrams/__init__.py
According to the implementation of `Diagram.__init__`, `outformat` can be either a `str` or a `list[str]`, but the function parameter type only accepts `str`. This PR fixes this issue.
> Fix parameter type of outformat

- .github/workflows/codeql-analysis.yml
codeQL v1 was deprecated: https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
CodeQL v2 will be deprecate soon so we will move to v3 -> https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
> Update version of codeql-analysis.yml

- diagrams/__init__.py
Hi @liancheng @gabriel-tessier . The `|` for type hint does not work for < Python 3.9. I fixed it with the Union function.
> fix: keep the backward compatibility for type hint

- README.md
- poetry.lock
- pyproject.toml
[Python 3.8 support end](https://endoflife.date/python) 1 month ago.
So, we updated the minimum required version to 3.9, which means it will no longer maintain backward compatibility with versions earlier than 3.9.
> env: update the required minimum Python version to 3.9

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Added [Dev Container](https://containers.dev/) support to automate the lifecycle of local development setup using [VSCode and containers](https://code.visualstudio.com/docs/devcontainers/containers). Based on the existing Dockerfile (copied under the new `.devcontainer` folder) the following VSCode extensions were added:
- Python, Python Debugger, Pylance (Microsoft extensions)
- Git Graph (mhutchie.git-graph)
- Resource Monitor (mutantdino.resourcemonitor)
- Diagrams Previewer (tehpeng.diagramspreviewer)
The new `.devcontainer/Dockerfile` additionally installs the following packages in base image:
- nodejs
- npm
!! The `docker/dev/Dockerfile` is no longer needed **but it's been left intact**. !!
> added devcontainer support for vscode

- docs/getting-started/examples.md
#1023 had a small number of mistakes, the most import of which broke the image links on the Examples page for the AWS on-premises examples
This PR corrects the issues and uses on-premises (or one instance of on-premise in the changelog) where needed
> docs: Fix incorrect on-premise refs from PR #1023

- diagrams/__init__.py
The `reverse` property was set incorrectly because it wasn't taken into account (`forward` argument was used)
> Fix `Edge.append` method

- pyproject.toml
We don't have an official CLI. But there was an added line for the command line config by [mistake](https://github.com/mingrammer/diagrams/pull/1050). I removed it.
> fix: remove unimplemented command-line config

- diagrams/cli.py
- docs/getting-started/installation.md
- pyproject.toml
- tests/test_cli.py
This changes addresses https://github.com/mingrammer/diagrams/issues/369 while providing a simple CLI entry point which can be used outside the virtual environment of the installed package.
This works well with for example with [pipx](https://pipxproject.github.io/pipx/).
> feat(scripts): provide `diagrams` CLI
